version: "3.8"

services:
  app:
    image: maven:3.8.8-eclipse-temurin-8
    container_name: spring_app
    volumes:
      - ./:/workspace
    working_dir: /workspace
    tty: true
    command: tail -f /dev/null
    depends_on:
      - db

  db:
    image: mariadb:11.4
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpw
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpw
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data: